apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-outline
  namespace: outline
spec:
  volumeName: pv-outline
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-outline
  namespace: outline
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/outline

    