apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: outline
spec:
  volumeName: pv-redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  namespace: outline
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/outline_postgres

    