apiVersion: v1
data:
  PASSWD: NjRmZjcxMzlhMDk5MWM4MWIzY2E1YzYwMTQ3YWU4OGJkNzEyNWQ2NTk2Zjk0ZDE4ZDU2OTQ3NDk4NzE4NjUxYQ==
  USER: dXNlcg==
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: outline
