apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: outline
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PASSWD
          - name: POSTGRES_DB
            value: outline
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-postgres
          resources: {}
      volumes:
        - name: pvc-postgres
          persistentVolumeClaim:
            claimName: pvc-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: outline
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
